### ISSUE TITLE
Not seeing option None

### ISSUE THREAD

**Issue by ult0** [Scrumplex/Steam-Play-None#1]
I created the `compatibility.d` folder under `~/.steam/steam/` and extracted the files there. After restarting my steam deck I am still not seeing the option for None. I do see a bunch of Proton versions and another option called Steam Linux Runtime

**Comment by Scrumplex** [comment]
The folder should be called `compatibilitytools.d` not `compatibility.d`. Can you try renaming that folder?

**Comment by ult0** [comment]
Oop, totally named it wrong. I was so focused on using the terrible steam deck keyboard that I forgot to add `tools` in the name. Works great now! Getting no spikes in the frame rate at all in the performance overlay.
