### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pslyman** [Scrumplex/Steam-Play-None#2]
Thanks for developing this! 

I followed the steps and got "None" to show up in the compatability list. However, the game (CrossCode in this case) won't start. Steam tries and just spins forever, and has to be restarted to close the spinner. Steam Linux Runtime doesn't work either (unless started outside Steam, from the desktop executable).

When I switch back to Proton, the game runs as it did before (not smoothly). Anything I can try to get it going?

**Comment by Scrumplex** [comment]
Huh interesting. If you switch between Proton and None, it should re-download the game. If it doesn't do that you could try manually uninstalling it

**Comment by pslyman** [comment]
It does re-download the game automatically, but Steam cannot open it. It just shows the Steam loading spinner until I force close it.

Update: just uninstalled, set it to None, re-download. Still won't run. I wonder if there was an OS update that broke it recently, I know the game hasn't been updated in a little while, so that wouldn't be the problem.

**Comment by pslyman** [comment]
I gave it another look and figured it out. For any idiot that can't get it to work (even though None is selected), do the following.

1. Set game compatibility mode to Linux Runtime.
2. In desktop mode, make sure the downloaded folder sits in /home/deck/.local/share/Steam/compatibilitytools.d/
If the Steam-Play-None folder doesn't exist inside of there (and instead just its contents), you did it wrong. The path goes /home/deck/.local/share/Steam/compatibilitytools.d/**Steam-Play-None** and _then_ the folder contents. "None" will show up in the compatibility list if you did it wrong, which was my issue.
3. Go into Game mode. Switch compatibility mode to "None".
4. Play the game.
